[package]
name = "markdown"
version = "1.0.0-alpha.16"
authors = ["Titus Wormer <tituswormer@gmail.com>"]
edition = "2018"
rust-version = "1.56"
description = "CommonMark compliant markdown parser in Rust with ASTs and extensions"
homepage = "https://github.com/wooorm/markdown-rs"
repository = "https://github.com/wooorm/markdown-rs"
license = "MIT"
keywords = ["commonmark", "markdown", "parse", "render", "tokenize"]
categories = ["compilers", "encoding", "parser-implementations", "parsing", "text-processing"]
include = ["src/", "license"]

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false

[features]
default = []
log = ["dep:log"]

[dependencies]
log = { version = "0.4", optional = true }
unicode-id = { version = "0.3", features = ["no_std"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
env_logger = "0.10"
serde_json = "1.0"
criterion = "0.5"
pretty_assertions = "1"
swc_core = { version = "0.86.0", features = [
  "ecma_ast",
  "ecma_visit",
  "ecma_parser",
  "common",
] }

[workspace]
members = ["generate"]
